function definput=arg_firwin(definput)
  
  definput.flags.wintype={ 'hanning','hann','sine','cosine','sqrthan', ...
                      'sqrthann','hamming', 'hammingacc','sqrtham','square','rect', ...
                      'sqrtsquare','sqrtrect', 'tria','bartlett', ...
                      'triangular','sqrttria','blackman','blackman2', ...
                      'nuttall','nuttall10','nuttall01','nuttall20', ...
                      'nuttall11','nuttall03', 'nuttall12','nuttall21', ...
                      'nuttall30', 'ogg','itersine'};
  

