[f,fs] =wavload('serj.wav'); 
a = 512; M = 2048;
%[f,fs] = gspi;
atoms =3e5;
Ls = numel(f);
L = dgtlength(Ls,a,M);
tfr = a*M/L;
step = 10000;
g = 'gauss';


[c1,fhat1,info1] = dgtrealmp(f,a,M,'mp','tol',1e-10,'atoms',atoms,...
                   'g1','gauss','atsellim',10000,...
                   'relresstep',step,'errexact','printdb',...
                   'relrestoldb',-80);
 info1
 info1.exitmsg
 20*log10(info1.relres)
% a = 256;
% [c2,fhat2,info2] = dgtrealmp(f,a,M,'localomp','tol',1e-4,'atoms',atoms,...
%                     'g1',g,...
%                     'printstep',step,'relresstep',step,'printdb');   
%     
% a = 128;
% [c3,fhat3,info3] = dgtrealmp(f,a,M,'localomp','tol',1e-4,'atoms',atoms,...
%                      'g1',g,...
%                      'printstep',step,'relresstep',step,'printdb'); 
                
% [c4,fhat4,info4] = dgtrealmp(f,a,M,'compllocalomp','tol',1e-4,'atoms',atoms,...
%                     'g1',g,...
%                     'printstep',step,'relresstep',step,'printdb'); 
            
% [c,relresmp2,fhat] = dgtrealmp(f,1024,M,'mp','tol',1e-5,'maxit',maxit,...
%                 'g1',{'hann',4096},...
%                 'relresstep',1000);
%             
% [c,relresmp3,fhat] = dgtrealmp(f,32,M,'mp','tol',1e-5,'maxit',maxit,...
%                 'g1',{'hann',128},...
%                 'relresstep',1000);
            
%plot(20*log10([info1.relres,info2.relres,info3.relres]))
%[c,relreslocmp] = dgtrealmp(f,a,M,'locomp','tol',1e-4,'maxit',maxit,...
%                    'relresstep',1000,'g1','hann');
% 

