%[f,fs] =wavload('serj.wav'); 
%f = f(1:fs);
[f,fs] =gspi;

a1 = 32; M1 = 128;
a2 = 1024; M2 = 16384;
a3 = 512; M3 = 2048;
a4 = 1024; M4 = 4096;
%[f,fs] = gspi;
atoms = 10000;
Ls = numel(f);
L = dgtlength(Ls,a2,M2);
tfr1 = a*M/L;
tfr2 = a2*M2/L;
step = 100;
g = 'gauss';


[c1,fhat1,info1] = dgtrealmp(f,'mp','tol',1e-3,'atoms',atoms,...
                   'g2',{'hann',256,2048},...
                   'atsellim',10000,...
                   'relresstep',step,'errappr','printdb',...
                   'relrestoldb',-45);
%                     'g3',{'gauss',tfr/2^2},...
%                    'g4',{'gauss',tfr/2^2},...
%                    'g5',{'gauss',tfr/2^2},...
%                    'g6',{'gauss',tfr/2^2},...              

 info1
 info1.exitmsg
 20*log10(info1.relres)
% a = 256;
% [c2,fhat2,info2] = dgtrealmp(f,a,M,'localomp','tol',1e-4,'atoms',atoms,...
%                     'g1',g,...
%                     'printstep',step,'relresstep',step,'printdb');   
%     
% a = 128;
% [c3,fhat3,info3] = dgtrealmp(f,a,M,'localomp','tol',1e-4,'atoms',atoms,...
%                      'g1',g,...
%                      'printstep',step,'relresstep',step,'printdb'); 
                
% [c4,fhat4,info4] = dgtrealmp(f,a,M,'compllocalomp','tol',1e-4,'atoms',atoms,...
%                     'g1',g,...
%                     'printstep',step,'relresstep',step,'printdb'); 
            
% [c,relresmp2,fhat] = dgtrealmp(f,1024,M,'mp','tol',1e-5,'maxit',maxit,...
%                 'g1',{'hann',4096},...
%                 'relresstep',1000);
%             
% [c,relresmp3,fhat] = dgtrealmp(f,32,M,'mp','tol',1e-5,'maxit',maxit,...
%                 'g1',{'hann',128},...
%                 'relresstep',1000);
            
%plot(20*log10([info1.relres,info2.relres,info3.relres]))
%[c,relreslocmp] = dgtrealmp(f,a,M,'locomp','tol',1e-4,'maxit',maxit,...
%                    'relresstep',1000,'g1','hann');
% 

